
mod_id=autoplant
curse_id=444013
curse_slug=auto-plant
mod_version=1.0.2
mod_name=autoplant
mod_group_id=com.lothrazar.autoplant
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
modrinth_id=auto-plant

flib_version=0.1.0
flib_file=8022223

